version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins
    tty: true
    build:
      context: .
      dockerfile: JenkinsDockerfile
    ports:
      - "0.0.0.0:49001:8080"
    volumes:
      - /home/docker/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  rancher:
    container_name: rancher
    image: rancher/rancher:stable
    tty: true
    ports:
      - "0.0.0.0:49002:80"
    volumes:
      - /home/docker/rancher:/var/lib/mysql
  registry:
    container_name: registry
    restart: always
    image: registry:2
    ports:
      - 49003:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    volumes:
      - /home/docker/registry/data:/var/lib/registry
      - /home/docker/registry/auth:/auth
      - /home/docker/certs/ssl:/certs