version: '3'
services:
  rancher:
    container_name: rancher
    image: rancher/server:stable
    tty: true
    ports:
      - "0.0.0.0:49002:8080"
    volumes:
      - /home/docker/rancher:/var/lib/mysql
