version: '3'
services:
  rancher:
    container_name: rancher
    image: rancher/rancher:stable
    tty: true
    ports:
      - "0.0.0.0:49002:80"
    volumes:
      - /home/docker/rancher:/var/lib/mysql
